### ISSUE TITLE
等一个vue版本！

### ISSUE THREAD

**Issue by zibirui** [ciaochaos/qrbtf#12]

**Comment by CPunisher** [comment]
react改vue整个项目都要重写啊
暂时没有开发计划

**Comment by StringKe** [comment]
@zibirui 你可以使用 https://github.com/gexin1/beautify-qrcode 。因为不依赖 react 所以 vue 可以直接通过生成 svg 的方式使用v-html渲染出来。

**Comment by StringKe** [comment]
@ciaochaos @CPunisher 

对于js多种不同的框架。
建议维护一个不基于框架的版本（使用范围和用途更广）。canvas在服务器可以使用node-canvas。

**Comment by CPunisher** [comment]
> @ciaochaos @CPunisher
> 
> 对于js多种不同的框架。
> 建议维护一个不基于框架的版本（使用范围和用途更广）。canvas在服务器可以使用node-canvas。

不基于框架的版本参考 https://github.com/gexin1/beautify-qrcode 已经写出来了
但是考虑到代码的易用性本项目并没有采用
另外，要写vue版本生成二维码的核心功能只是其中一个部分，整体网页的组件和数据绑定基本都要重写
