### ISSUE TITLE
老哥，能问下你的qrbtf.com的logo是用工具生成的还是手写的svg吗

### ISSUE THREAD

**Issue by aninchiron** [ciaochaos/qrbtf#16]

**Comment by aninchiron** [comment]
找到了https://github.com/codrops/AnimatedLetters/

**Comment by BlueSu007** [comment]
你们这个网站是不是闲的啊，给我发20多封邮件，我邮箱是用来骚扰的啊
而且没有给我解答的问题啊
我承认这玩意很好使，但是也不能发这么多邮件啊
改善一下吧
----- 原始邮件 -----
发件人：aninchiron <notifications@github.com>
收件人：ciaochaos/qrbtf <qrbtf@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re:_[ciaochaos/qrbtf]_老哥，能问下你的qrbtf.com的logo是用工具生成的还是手写的svg吗_(#16)
日期：2020年09月29日 17点34分


Closed #16.

&mdash;

**Comment by CPunisher** [comment]
> 你们这个网站是不是闲的啊，给我发20多封邮件，我邮箱是用来骚扰的啊 而且没有给我解答的问题啊 我承认这玩意很好使，但是也不能发这么多邮件啊 改善一下吧 ----- 原始邮件 ----- 发件人：aninchiron <notifications@github.com> 收件人：ciaochaos/qrbtf <qrbtf@noreply.github.com> 抄送人：Subscribed <subscribed@noreply.github.com> 主题：Re:_[ciaochaos/qrbtf]_老哥，能问下你的qrbtf.com的logo是用工具生成的还是手写的svg吗_(#16) 日期：2020年09月29日 17点34分 Closed #16. &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

修改一下这个项目Watch的类别就行了
