### ISSUE TITLE
这个可以在Vue项目里面使用吗？

### ISSUE THREAD

**Issue by zhangyi886** [ciaochaos/qrbtf#18]
如题
另外还有一个问题，商用需要付费吗？如果需要，如何付费购买

**Comment by CPunisher** [comment]
这是一个完整的react web项目
你可以在遵循GPL协议下参考使用项目中的代码（或者直接使用网站的功能，生成的二维码图片可以随意使用）
如果想在自己的项目里添加生成二维码的功能，请参考[react-qrbtf](https://github.com/CPunisher/react-qrbtf)
但是npm package是基于react编写的，所以Vue应该是无法使用的
想在Vue中使用可调用后端接口，参考 #6 #13

**Comment by CPunisher** [comment]
开源项目无需付费使用，不过如果帮助到你了可以提供赞助🙂
