### ISSUE TITLE
您好，react模块是否已集成所有样式了，可否出个教程或api使用

### ISSUE THREAD

**Issue by wangji817** [ciaochaos/qrbtf#26]
![image](https://user-images.githubusercontent.com/18747310/126581317-dfae79e1-b230-4176-92d0-25b692c21f5d.png)
看示例只有一个简单的引用代码，可否针对各个参数使用进行一个说明？感谢分享

**Comment by CPunisher** [comment]
参考 [react-qrtbf-docs](https://cpunisher.github.io/react-qrbtf/)
