### ISSUE TITLE
windows不能运行

### ISSUE THREAD

**Issue by pifuant** [ciaochaos/qrbtf#5]
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 1862 packages in 24.579s

58 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by pifuant** [comment]
move the dependency array. If 'dispatch' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps

./src/utils/util.js
  Line 20:19:  Expected '===' and instead saw '=='  eqeqeq

./src/reducers/index.js
  Line 24:38:  Expected '===' and instead saw '=='  eqeqeq
  Line 53:31:  Expected '!==' and instead saw '!='  eqeqeq

./src/components/renderer/RendererBase.js
  Line 29:37:   Expected '===' and instead saw '=='  eqeqeq
  Line 31:33:   Expected '===' and instead saw '=='  eqeqeq
  Line 31:80:   Expected '===' and instead saw '=='  eqeqeq
  Line 31:126:  Expected '===' and instead saw '=='  eqeqeq
  Line 32:26:   Expected '===' and instead saw '=='  eqeqeq
  Line 34:31:   Expected '===' and instead saw '=='  eqeqeq
  Line 36:31:   Expected '===' and instead saw '=='  eqeqeq
  Line 39:38:   Expected '===' and instead saw '=='  eqeqeq
  Line 40:29:   Expected '===' and instead saw '=='  eqeqeq
  Line 42:36:   Expected '===' and instead saw '=='  eqeqeq
  Line 45:36:   Expected '===' and instead saw '=='  eqeqeq
  Line 56:38:   Expected '===' and instead saw '=='  eqeqeq
  Line 57:29:   Expected '===' and instead saw '=='  eqeqeq
  Line 62:26:   Expected '===' and instead saw '=='  eqeqeq
  Line 64:31:   Expected '===' and instead saw '=='  eqeqeq
  Line 66:31:   Expected '===' and instead saw '=='  eqeqeq

./src/components/renderer/RendererImage.js
  Line 33:33:   Expected '===' and instead saw '=='  eqeqeq
  Line 33:80:   Expected '===' and instead saw '=='  eqeqeq
  Line 33:126:  Expected '===' and instead saw '=='  eqeqeq
  Line 35:30:   Expected '===' and instead saw '=='  eqeqeq
  Line 37:35:   Expected '===' and instead saw '=='  eqeqeq
  Line 40:30:   Expected '===' and instead saw '=='  eqeqeq
  Line 42:35:   Expected '===' and instead saw '=='  eqeqeq
  Line 46:38:   Expected '===' and instead saw '=='  eqeqeq
  Line 48:33:   Expected '===' and instead saw '=='  eqeqeq
  Line 50:40:   Expected '===' and instead saw '=='  eqeqeq
  Line 54:40:   Expected '===' and instead saw '=='  eqeqeq
  Line 68:38:   Expected '===' and instead saw '=='  eqeqeq
  Line 70:33:   Expected '===' and instead saw '=='  eqeqeq
  Line 74:33:   Expected '===' and instead saw '=='  eqeqeq
  Line 82:30:   Expected '===' and instead saw '=='  eqeqeq
  Line 84:35:   Expected '===' and instead saw '=='  eqeqeq
  Line 87:30:   Expected '===' and instead saw '=='  eqeqeq
  Line 89:35:   Expected '===' and instead saw '=='  eqeqeq

./src/components/renderer/Renderer25D.js
  Line 33:37:   Expected '===' and instead saw '=='          eqeqeq
  Line 34:38:   Expected '===' and instead saw '=='          eqeqeq
  Line 34:82:   Expected '===' and instead saw '=='          eqeqeq
  Line 36:214:  Unexpected string concatenation of literals  no-useless-concat
  Line 37:215:  Unexpected string concatenation of literals  no-useless-concat
  Line 41:209:  Unexpected string concatenation of literals  no-useless-concat
  Line 42:210:  Unexpected string concatenation of literals  no-useless-concat

./src/containers/style/StyleListViewer.js
  Line 36:43:  Expected '===' and instead saw '=='  eqeqeq

./src/components/renderer/RendererDSJ.js
  Line 37:37:  Expected '===' and instead saw '=='  eqeqeq
  Line 39:38:  Expected '===' and instead saw '=='  eqeqeq
  Line 40:29:  Expected '===' and instead saw '=='  eqeqeq
  Line 42:36:  Expected '===' and instead saw '=='  eqeqeq
  Line 50:38:  Expected '===' and instead saw '=='  eqeqeq
  Line 51:29:  Expected '===' and instead saw '=='  eqeqeq

./src/utils/navigatorUtils.js
  Line 3:36:  Expected '===' and instead saw '=='  eqeqeq

./src/utils/qrcodeHandler.js
  Line 52:25:  Expected '===' and instead saw '=='  eqeqeq
  Line 52:35:  Expected '===' and instead saw '=='  eqeqeq
  Line 63:29:  Expected '===' and instead saw '=='  eqeqeq
  Line 63:39:  Expected '===' and instead saw '=='  eqeqeq
  Line 70:15:  Expected '!==' and instead saw '!='  eqeqeq

./src/components/style/Renderer.js
  Line 9:33:  Expected '===' and instead saw '=='  eqeqeq
  Line 9:63:  Expected '===' and instead saw '=='  eqeqeq

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by CPunisher** [comment]
我这边是没问题的
如果是 `npm install` 出现网络问题，可以考虑使用cnpm淘宝镜像
第二个是`npm start`时的warning，主要是代码写的不太符合es6规范被eslint检测了，理论上讲是不会影响正常运行的
不过看你能正常`npm start`说明`npm install`应该把modules都正常安装了把。。
看看`npm start`后访问`http://localhost:3000`正不正常

**Comment by pifuant** [comment]
well, 可以了， thanks
