### ISSUE TITLE
请问一下npm包的形式有没有考虑呢

### ISSUE THREAD

**Issue by gexin1** [ciaochaos/qrbtf#8]

**Comment by ciaochaos** [comment]
已经差不多做好啦，看这里 [react-qrbtf](https://github.com/cpunisher/react-qrbtf)
```sh
yarn add react-qrbtf
```

**Comment by gexin1** [comment]
谢谢了
我在你的开源代码上改了一个不依赖框架的  我们在小程序上使用的😄   [demo](https://github.com/gexin1/beautify-qrcode)

**Comment by ciaochaos** [comment]
> 谢谢了
> 
> 我在你的开源代码上改了一个不依赖框架的  我们在小程序上使用的😄   [demo](https://github.com/gexin1/beautify-qrcode)

Cool！
