### ISSUE TITLE
是否可以加上 Credit 信息

### ISSUE THREAD

**Issue by IceCodeNew** [ciaochaos/qrbtf#9]
不是要出警什么的。只是在 v2ex 上看见了宣发，然后有人和我一样注意到这个项目是基于 qrcode-generator 的。
希望把 credit 信息写出来，是方便其他人对这个 repo 的质量做评估。遇到问题时也可以去相关的库里找找解答。
就像写论文一定要有参考文献一样，拜托加上 credit 信息吧（

**Comment by ciaochaos** [comment]
非常感谢，已经加上了～

**Comment by IceCodeNew** [comment]
谢谢~
